name = "bb-bale-chambers"
compatibility_date = "2024-04-01"
pages_build_output_dir = "dist"

# Cloudflare D1 Database Binding for B. B. Bale & Co. Chambers
# env.DB is the server-side binding to Cloudflare D1
[[d1_databases]]
binding = "DB"
database_name = "bbbale"
database_id = "60c1e783-fa57-48b3-9b37-8d0041a4e80a"
migrations_dir = "migrations"

